version: '3.1'
services:
    evqueue-core:
        build:
            context: ../evqueue-core
            args:
                branch: master
        ports:
            - "${EVQUEUE_API_PORT}:5000"
            - "${EVQUEUE_WS_PORT}:5001"
            - "${EVQUEUE_ELOGS_PORT}:5002"

        environment:
            mysql_host: mariadb
            mysql_user: root
            mysql_password: root
        
        depends_on:
            - mariadb
    
    mariadb:
        image: "mariadb:10.8"
        environment:
            MYSQL_ROOT_PASSWORD: root
    
    evqueue-frontend-react:
        build:
            context: ../evqueue-frontend-react
            args:
                branch: master
        
        ports:
            - "${EVQUEUE_HTTP_PORT}:80"
        
        depends_on:
            - evqueue-core
