version: '3.0'
services:
    evqueue-core:
        build:
            context: ../evqueue-core
            args:
                branch: master
        ports:
            - "${EVQUEUE_API_PORT}:5000"
            - "${EVQUEUE_WS_PORT}:5001"

        environment:
            mysql_host: mariadb
            mysql_user: evqueue
            mysql_password: evqueue
        
        depends_on:
            - mariadb
    
    mariadb:
        image: "mariadb:10.5"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: evqueue
            MYSQL_USER: evqueue
            MYSQL_PASSWORD: evqueue
    
    evqueue-frontend-react:
        build:
            context: ../evqueue-frontend-react
            args:
                branch: master
        
        ports:
            - "${EVQUEUE_HTTP_PORT}:80"
        
        depends_on:
            - evqueue-core
